[build]
  publish = "public" # Ajuste para "." se os arquivos estão na raiz

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' 'data:image/*'; font-src 'self'; object-src 'none'; media-src 'none'; frame-src 'none'; connect-src 'self'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'; block-all-mixed-content; upgrade-insecure-requests;"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=(), usb=(), accelerometer=(), ambient-light-sensor=(), autoplay=(), battery=(), clipboard-read=(self), clipboard-write=(self), fullscreen=(self), gamepad=(), gyroscope=(), magnetometer=(), midi=(), notifications=(), push=(), speaker=(), sync-xhr=(), vibrate=(), web-share=()"
    Cross-Origin-Resource-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"
    Cache-Control = "no-store, no-cache, must-revalidate, private"
    Pragma = "no-cache"
    Expires = "0"
    Expect-CT = "max-age=86400, enforce, report-uri='https://keyspirezmdsec.report-uri.com/r/d/ct/enforce'"
    X-DNS-Prefetch-Control = "off"
    Server = ""
    X-Powered-By = ""
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/index.html"
  [headers.values]
    Content-Type = "text/html; charset=UTF-8"
    Cache-Control = "no-store, no-cache, must-revalidate, private"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Cross-Origin-Resource-Policy = "same-origin"

[[headers]]
  for = "/keyspire.js"
  [headers.values]
    Content-Type = "application/javascript; charset=UTF-8"
    Cache-Control = "no-store, no-cache, must-revalidate, private"
    X-Content-Type-Options = "nosniff"
    Cross-Origin-Resource-Policy = "same-origin"

[[headers]]
  for = "/keyspire.css"
  [headers.values]
    Content-Type = "text/css; charset=UTF-8"
    Cache-Control = "no-store, no-cache, must-revalidate, private"
    X-Content-Type-Options = "nosniff"
    Cross-Origin-Resource-Policy = "same-origin"

[[headers]]
  for = "/*.json|/*.toml|/*.env"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
    Access-Control-Allow-Origin = "none"
    Cache-Control = "no-store, no-cache, must-revalidate, private"

[[redirects]]
  from = "http://keyspirezmdsec.netlify.app/*"
  to = "https://keyspirezmdsec.netlify.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = { "Role" = "anonymous" }
