# Configuração do build
[build]
  publish = "dist"  # Ajuste para o diretório de saída do seu projeto (ex.: "build", "public")
  command = "npm run build"  # Ajuste para o comando de build do seu projeto (ex.: "yarn build")

# Configuração de cabeçalhos para todas as rotas
[[headers]]
  for = "/*"  # Aplica a todas as páginas do site
  [headers.values]
    # Política de Segurança de Conteúdo (Content-Security-Policy)
    # Protege contra XSS, permitindo apenas recursos confiáveis
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'self'; form-action 'self'; base-uri 'self';"
    
    # X-Frame-Options
    # Protege contra clickjacking, permitindo enquadramento apenas pelo mesmo origem
    X-Frame-Options = "SAMEORIGIN"
    
    # X-Content-Type-Options
    # Impede MIME-sniffing, forçando o tipo de conteúdo declarado
    X-Content-Type-Options = "nosniff"
    
    # Política de Referência (Referrer-Policy)
    # Controla informações enviadas no cabeçalho Referer
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Política de Permissões (Permissions-Policy)
    # Restringe acesso a recursos sensíveis do navegador
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=(), usb=()"
    
    # HSTS (força HTTPS por 1 ano, incluindo subdomínios)
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # Sem cache para páginas dinâmicas (essencial para dados sensíveis)
    Cache-Control = "no-store, no-cache, must-revalidate, private"

# Configuração de cabeçalhos para arquivos estáticos
[[headers]]
  for = "/assets/*"  # Ajuste para o caminho dos seus arquivos estáticos (ex.: "/static/*", "/js/*")
  [headers.values]
    # Cache longo para arquivos imutáveis
    Cache-Control = "public, max-age=31536000, immutable"
    # Mantém segurança em assets
    X-Content-Type-Options = "nosniff"

# Redirecionamento para garantir HTTPS
[[redirects]]
  from = "http://keyspirezmdsec.netlify.app/*"
  to = "https://keyspirezmdsec.netlify.app/:splat"
  status = 301
  force = true

# Redirecionamento opcional para raiz (se necessário)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
