# Configuração do build (ajustável conforme o framework usado)
[build]
  publish = "dist" # Diretório de saída (ex.: "dist" para Vite/React, "public" para outros)
  command = "npm run build" # Comando de build, ajuste se necessário

# Configuração de cabeçalhos para todas as rotas
[[headers]]
  for = "/*" # Aplica a todas as páginas
  [headers.values]
    # Política de Segurança de Conteúdo (Content-Security-Policy)
    # Protege contra XSS permitindo apenas fontes confiáveis
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'self'; form-action 'self'; base-uri 'self';"
    
    # X-Frame-Options
    # Protege contra clickjacking permitindo apenas enquadramento pelo mesmo origem
    X-Frame-Options = "SAMEORIGIN"
    
    # X-Content-Type-Options
    # Impede MIME-sniffing, forçando o tipo de conteúdo declarado
    X-Content-Type-Options = "nosniff"
    
    # Política de Referência (Referrer-Policy)
    # Controla informações enviadas no cabeçalho Referer
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Política de Permissões (Permissions-Policy)
    # Restringe acesso a recursos sensíveis do navegador
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=(), usb=()"
    
    # HSTS (adicional para forçar HTTPS)
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # Cache para páginas dinâmicas
    Cache-Control = "no-store, no-cache, must-revalidate"

# Configuração específica para arquivos estáticos
[[headers]]
  for = "/assets/*" # Aplica a arquivos estáticos (ajuste o caminho conforme sua estrutura)
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" # Cache de 1 ano para arquivos imutáveis
    X-Content-Type-Options = "nosniff" # Mantém segurança em assets

# Redirecionamento para HTTPS
[[redirects]]
  from = "http://keyspirezmdsec.netlify.app/*"
  to = "https://keyspirezmdsec.netlify.app/:splat"
  status = 301
  force = true
